### ISSUE TITLE
geo_id no filtra

### ISSUE THREAD

**Issue by PabloBarrancoEngie** [datons/python-esios#1]
Hola,
He hecho una consulta con los geo_id y no me los filtra
```
inicio = pd.Timestamp(inicio, tz='Europe/Brussels').replace(microsecond=0)
fin = pd.Timestamp(fin, tz='Europe/Brussels').replace(microsecond=0)
inicio = str(inicio).replace(" ","T")
fin = str(fin).replace(" ","T")

data = client.get(indicator_id=600,start_date=inicio,end_date=fin,geo_ids=[1,3])
```
Gracias!

**Comment by jsulopzs** [comment]
Gracias por el aviso @PabloBarrancoEngie. Se me habían traspapelado los corchetes `[]` en alguna actualización.

Si actualizas la librería con `pip install -U python-esios`, luego podrás ejecutar el código aplicando filtros por `geo_id` sin problema.

**Comment by PabloBarrancoEngie** [comment]
Hola Jesus, con la actualización al intentar importar la libreria:
`from esios.endpoints import Indicators, Archives`

me dá el siguiente error:

> ModuleNotFoundError: No module named 'esios.endpoints'; 'esios' is not a package

**Comment by jsulopzs** [comment]
Creo que estás instalando `python-esios` en un Python diferente.

Te explico aquí cómo solucionarlo: https://www.loom.com/share/3c275aeaeb8e4465ab8b0fc431cb2ad5

Cualquier cosa, me dices sin problema.

**Comment by PabloBarrancoEngie** [comment]
Hola Jesus, resulta que tenía un archivo yo esisos.py de mis request que mi entorno estaba entendiendo como origen de la librerira. Por eso no encontraba el modulo. He renombrado mi archivo y ya funciona.
Gracias!!

**Comment by jsulopzs** [comment]
It happens to the best! Un placer ;)
